# news_digest.py
import asyncio
import datetime
from config import Config
from search_service import SearchService
from analyzer import GEMINI_CLIENT, OPENAI_CLIENT # 假设analyzer中有这些客户端初始化，或在此处重新初始化
from notification import send_email # 复用现有的邮件发送函数
import os

# 定义 Swiss Style (格栅主义) 风格的 HTML 模板
def generate_swiss_style_html(confirmed_news, rumors, date_str):
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <style>
        body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f0f0f0; color: #333; margin: 0; padding: 20px; }}
        .container {{ max-width: 800px; margin: 0 auto; background: #fff; padding: 40px; border-top: 5px solid #ff4500; }}
        .header {{ margin-bottom: 40px; border-bottom: 2px solid #000; padding-bottom: 20px; }}
        h1 {{ font-size: 36px; font-weight: 700; letter-spacing: -1px; margin: 0; text-transform: uppercase; }}
        .date {{ font-size: 14px; font-weight: 400; color: #666; margin-top: 5px; }}
        .grid-section {{ margin-bottom: 50px; }}
        .section-title {{ font-size: 12px; font-weight: 700; text-transform: uppercase; border-bottom: 1px solid #000; margin-bottom: 20px; padding-bottom: 5px; display: inline-block; }}
        ul {{ list-style-type: none; padding: 0; margin: 0; }}
        li {{ margin-bottom: 15px; font-size: 14px; line-height: 1.4; display: flex; align-items: baseline; }}
        .number {{ font-weight: 700; margin-right: 15px; min-width: 20px; color: #ff4500; }}
        .content {{ color: #000; }}
        .footer {{ font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 20px; margin-top: 40px; }}
    </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Daily Securities Brief</h1>
                <div class="date">{date_str} | China Market Edition</div>
            </div>
            
            <div class="grid-section">
                <div class="section-title">01 / Confirmed News (Reliable Sources)</div>
                <ul>
                    {confirmed_news}
                </ul>
            </div>
            
            <div class="grid-section">
                <div class="section-title">02 / Market Rumors (Discussions & Speculation)</div>
                <ul>
                    {rumors}
                </ul>
            </div>
            
            <div class="footer">
                Generated by AI Stock Analysis System | Source: Global & Local Media
            </div>
        </div>
    </body>
    </html>
    """
    return html_content

async def run_news_digest():
    print("开始执行早报新闻抓取...")
    
    # 1. 搜索数据 (利用现有的 search_service)
    # 注意：需确保 .env 中配置了 TAVILY_API_KEYS 或 BOCHA_API_KEYS [2]
    searcher = SearchService() 
    
    # 构造搜索关键词，覆盖过去24小时
    query_confirmed = "中国证券市场 最新重磅新闻 过去24小时 新浪财经 东方财富 Reuters Bloomberg SCMP"
    query_rumors = "中国股市 市场传闻 小道消息 资金流向 猜测 过去24小时"
    
    print("正在搜索新闻和传闻...")
    # 这里假设 search_service 有一个 search 方法，如果原项目方法名为 search_news，请相应修改
    results_confirmed = await searcher.search(query_confirmed) 
    results_rumors = await searcher.search(query_rumors)
    
    # 2. LLM 分析与筛选 (复用 analyzer 的逻辑或直接调用 LLM)
    # 构造 Prompt
    prompt = f"""
    你是一个专业的金融新闻编辑。请根据以下搜索结果，整理两份列表。
    
    搜索结果 - 权威新闻: {results_confirmed}
    搜索结果 - 市场传闻: {results_rumors}
    
    任务要求：
    1. **权威新闻列表**：筛选20条最重要的中国证券新闻。来源必须可靠（如新浪、Reuters、政府网站），排除猜测。按重要性排序。
    2. **市场传闻列表**：筛选20条最新的市场传闻或热度讨论。包含未经证实的消息。按热度排序。
    3. **格式严格要求**：
       - 不要标题，每条仅用**一句话概括**核心内容。
       - 不需要Markdown格式，直接输出纯文本内容，方便我后续处理。
       - 输出格式模板如下（HTML列表项格式）：
         SECTION_1_START
         <li><span class="number">01</span><span class="content">新闻内容1...</span></li>
         <li><span class="number">02</span><span class="content">新闻内容2...</span></li>
         ...
         SECTION_1_END
         SECTION_2_START
         <li><span class="number">01</span><span class="content">传闻内容1...</span></li>
         ...
         SECTION_2_END
    """

    print("正在通过 LLM 生成摘要...")
    # 调用 LLM (这里使用项目中配置的 Gemini 或 OpenAI)
    # 代码需根据 analyzer.py 中的具体实现调整，以下为伪代码示例
    from analyzer import LLM_CLIENT # 假设你从 analyzer 导出了客户端
    response = LLM_CLIENT.generate_content(prompt) # 或者是 chat.completions.create
    content = response.text

    # 3. 解析 LLM 返回内容
    try:
        news_part = content.split("SECTION_1_START")[3].split("SECTION_1_END").strip()
        rumor_part = content.split("SECTION_2_START")[3].split("SECTION_2_END").strip()
    except IndexError:
        print("LLM 格式输出错误，发送原始内容")
        news_part = "<li>解析错误，请查看日志</li>"
        rumor_part = "<li>解析错误，请查看日志</li>"

    # 4. 生成 HTML
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    html_body = generate_swiss_style_html(news_part, rumor_part, today)

    # 5. 发送邮件 (复用 notification.py)
    # 确保 .env 中配置了 EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECEIVERS [4]
    print("正在发送邮件...")
    try:
        send_email(
            title=f"【证券早报】{today} 市场关键情报 (20条新闻+20条传闻)",
            content=html_body,
            content_type="html" # 确保 notification.py 支持 HTML 格式发送，一般需将 MIMEText 的第二个参数设为 'html'
        )
        print("邮件发送成功！")
    except Exception as e:
        print(f"邮件发送失败: {e}")

if __name__ == "__main__":
    asyncio.run(run_news_digest())
