# news_digest.py
import os
import asyncio
import logging
from datetime import datetime
import pytz

# 复用原有项目的模块 (假设项目结构如你提供的文件列表所示)
from config import Config
from search_service import SearchService
from analyzer import GeminiAnalyzer  # 或原项目中的 AI 分析类
from notification import EmailNotifier # 假设通知模块有名为 EmailNotifier 的类或发送函数

# 配置日志
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

async def generate_morning_brief():
    logger.info("开始生成每日市场晨报...")
    
    # 1. 初始化服务
    cfg = Config()
    search_service = SearchService(cfg)
    llm_analyzer = GeminiAnalyzer(cfg) # 假设这是初始化方式
    
    # 2. 执行广度搜索 (针对过去24小时)
    # 搜索词旨在覆盖正规新闻和市场传闻
    search_queries = [
        "过去24小时中国证券市场重大利好利空新闻",
        "latest Chinese stock market news and rumors last 24 hours",
        "A股 港股 市场传闻 小作文 最新",
        "权威财经媒体头条 24小时内 新浪财经 东方财富 财联社",
        "China stock market regulation updates and insider rumors"
    ]
    
    logger.info("正在搜索全网新闻...")
    # 假设 search_service 有一个综合搜索方法，如果没有，通常是 search(query)
    # 这里我们聚合搜索结果
    raw_context = ""
    for query in search_queries:
        results = await search_service.search(query) # 根据实际代码调整调用方式
        raw_context += f"\nSearch Query: {query}\nResults: {results}\n"

    # 3. 构建 Prompt (核心：格栅主义风格 HTML + 分类筛选)
    current_date = datetime.now(pytz.timezone('Asia/Shanghai')).strftime('%Y-%m-%d')
    
    prompt = f"""
    You are a professional financial editor specializing in the Chinese stock market. 
    Analyze the following raw search results from the past 24 hours:
    {raw_context}

    **Task:**
    Create a "Morning Market Brief" for {current_date}. 
    Classify content into two strict categories:
    1. **Market Facts (Reliable News):** Select the 20 most important, confirmed news items from authoritative sources (Gov, Reuters, Sina Finance, etc.). No speculation.
    2. **Market Rumors (The Grapevine):** Select the 20 hottest unconfirmed market rumors ("小作文", speculation, buzz) currently discussed in the community.

    **Requirements:**
    - **Language:** Chinese (Simplified).
    - **Format:** Output PURE HTML code. No markdown code blocks (```html), just the raw HTML string.
    - **Style:** "Swiss Style" (International Typographic Style). Minimalist, clean, strictly aligned, sans-serif, high contrast.
    - **Content:** ONE sentence per item. Numbered lists.
    
    **HTML Template Structure to fill:**
    Use an internal CSS within the HTML.
    - Font: Helvetica, Arial, sans-serif.
    - Layout: A clean container (max-width 600px).
    - Header: Big, bold date and title "{current_date} 市场晨报".
    - Section 1: "🏛️ 市场要闻 (Facts)" - distinct header style.
    - Section 2: "🗣️ 市场传闻 (Rumors)" - distinct header style (maybe different accent color).
    - List Items: Cleanly spaced, clear numbering.
    - Footer: "Generated by Gemini AI".

    Generate the HTML now.
    """

    logger.info("正在通过 LLM 生成分析报告...")
    # 调用 LLM
    html_content = await llm_analyzer.chat(prompt) # 假设这是调用 LLM 的方法

    # 清理可能存在的 Markdown 标记 (以防万一)
    html_content = html_content.replace("```html", "").replace("```", "").strip()

    # 4. 发送邮件
    logger.info("正在发送邮件...")
    subject = f"【市场晨报】{current_date} A股/港股 20条要闻+20条传闻"
    
    # 假设 notification.py 里有发送邮件的逻辑
    # 如果原逻辑耦合度高，我们直接使用原项目的邮件配置发送
    try:
        # 这里需要根据 notification.py 的实际代码调整
        # 假设它是基于环境变量配置的
        notifier = EmailNotifier(cfg)
        await notifier.send(subject, html_content, mime_type="html") 
        logger.info("邮件发送成功！")
    except Exception as e:
        logger.error(f"邮件发送失败: {e}")
        # 如果原来的类很难调用，可以直接在这里写一个简单的 SMTP 发送逻辑作为备选

if __name__ == "__main__":
    asyncio.run(generate_morning_brief())
